export { default as Icon } from './Icon'
export { default as StyledIcon } from './Icon.Styled'

export { default as ReactIcon } from './React'
export { default as TSIcon } from './TypeScript'
export { default as NextIcon } from './Next'
export { default as NodeIcon } from './Node'
export { default as ReduxIcon } from './Redux'
export { default as MongoIcon } from './Mongo'
export { default as FirebaseIcon } from './Firebase'
export { default as MySQLIcon } from './MySQL'
export { default as PostgresIcon } from './Postgres'
export { default as AWSIcon } from './AWS'
